# /etc/nginx/snippets/seoloop-fastcgi.conf
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root/index.php;
fastcgi_param SCRIPT_NAME /index.php;
fastcgi_pass unix:/run/php/seoloop-api.sock;
fastcgi_read_timeout 35s;
